package nl.spijkerman.ivo.horoscopeapp.activities;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import nl.spijkerman.ivo.horoscopeapp.R;
import nl.spijkerman.ivo.horoscopeapp.models.Horoscope;

public class MainActivity extends AppCompatActivity {
    private ListView listViewZodiacSigns;
    private ArrayAdapter<Horoscope> listViewZodiacSignsAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // <auto-generated>
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // </auto-generated>


    }
}
