package nl.spijkerman.ivo.horoscopeapp.activities;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import nl.spijkerman.ivo.horoscopeapp.R;
import nl.spijkerman.ivo.horoscopeapp.controller.HoroscopeController;
import nl.spijkerman.ivo.horoscopeapp.models.Horoscope;

public class MainActivity extends AppCompatActivity implements AdapterView.OnItemClickListener {
    private ListView listViewZodiacSigns;
    private ArrayAdapter<Horoscope> listViewZodiacSignsAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // <auto-generated>
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // </auto-generated>

        listViewZodiacSigns = findViewById(R.id.list_view_zodiac_signs);
        listViewZodiacSignsAdapter = new ArrayAdapter<>(
                this,
                R.layout.simple_list_item,
                HoroscopeController.getAll()
        );

        listViewZodiacSigns.setAdapter(listViewZodiacSignsAdapter);
        listViewZodiacSigns.setOnItemClickListener(this);
    }

    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Intent intent = new Intent(this, DetailActivity.class);
        intent.putExtra(DetailActivity.EXTRA_ZODIAC_ID, id);
        startActivity(intent);
    }
}
